python3 factor_selection.py --factor_code adratio
python3 factor_selection.py --factor_code arturndays
python3 factor_selection.py --factor_code arturnover
python3 factor_selection.py --factor_code bips
python3 factor_selection.py --factor_code business_income
python3 factor_selection.py --factor_code bvps
python3 factor_selection.py --factor_code cashflowratio
python3 factor_selection.py --factor_code cashratio
python3 factor_selection.py --factor_code cf_liabilities
python3 factor_selection.py --factor_code cf_nm
python3 factor_selection.py --factor_code cf_sales
python3 factor_selection.py --factor_code currentasset_days
python3 factor_selection.py --factor_code currentasset_turnover
python3 factor_selection.py --factor_code currentratio
python3 factor_selection.py --factor_code epcf
python3 factor_selection.py --factor_code eps
python3 factor_selection.py --factor_code epsg
python3 factor_selection.py --factor_code gross_profit_rate
python3 factor_selection.py --factor_code icratio
python3 factor_selection.py --factor_code inventory_turnover
python3 factor_selection.py --factor_code mbrg
python3 factor_selection.py --factor_code nav
python3 factor_selection.py --factor_code net_profit_ratio
python3 factor_selection.py --factor_code net_profits
python3 factor_selection.py --factor_code nprg
python3 factor_selection.py --factor_code quickratio
python3 factor_selection.py --factor_code rateofreturn
python3 factor_selection.py --factor_code roe
python3 factor_selection.py --factor_code seg
python3 factor_selection.py --factor_code sheqratio
